name: Create Diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  create-diagram:
    name: Create Diagram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update Diagram 
        uses: githubocto/repo-visualizer@0.8.2
        with:
          excluded_paths: "ignore,.github,dist,nobe_modules"
          output_file: "diagram.svg"
          branch: main
